sudo: false
language: rust
rust:
- nightly
- beta
- stable
matrix:
  allow_failures:
    - rust: beta
    - rust: stable
    - rust: nightly
      env: TRAVIS_CARGO_NIGHTLY_FEATURE=lint
  exclude:
    - rust: beta
      env: TRAVIS_CARGO_NIGHTLY_FEATURE=lint
    - rust: stable
      env: TRAVIS_CARGO_NIGHTLY_FEATURE=lint
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo build &&
  travis-cargo test  &&
  travis-cargo bench &&
  travis-cargo --only stable doc
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - libblas-dev
    - fglrx
    - opencl-headers
    - binutils-dev
    - nvidia-opencl-dev

after_success:
- travis-cargo doc-upload
- travis-cargo coveralls --no-sudo --verify
notifications:
  email:
    on_success: never
env:
  global:
    - secure: QcJ9u0BrVpvjYnerd/3dukvM+GLFQNikIoDHhtKjVenuM2ozZtW6+/RyyXVC1YMh/SghwTnu4Kcnv1sdmwuiC5KWdPoppfalXdxafPkl5PGEfTOexe6L5UAJNW6BdA4lbRKM3xnaUg0Guq6x6tD/zdABIkh8nym/gRLGKT40e9Xitkf6wUQqPBHTGZimip59qg5Fty8lAD48pCBEXynJm+ihA2tz6EDhp0/7wvieHyEl/FqNwvUL5+Z9EeTzEJfKNF8PA5DTHkgeXgeCnWKLm8cCdPEziRZlgdQtvIW27oZBkNTQGHyqI9/tVYhaW4AeKstzE5BoJuyRzmerWYRQCNiz8bgyAjc5HnpWLJPmPSFaGBWTRzwYwUk/iOUP4YEZiN3p0Xj1sKgSB0TA2AjKWND7cufwjrW8NdPdZ3hURVOnM8DHYSQMm2HOfbUNnkw+P5M8n+flT2HKWFdnPhJ3n12rDlLYdHeg9PQ3emJ6kE8Y/jrNT+6yZRrSwLQnsV0uU8Ii44MFQHpdUOGuOIxZFGh9rjKsUwhruUpGtbwI4FWPOqiQJvIaBFY1IUjIVlVCZevvIG3fPXvPksIEKwK93hM/ThDi2PLq2qwBpA87RNfKxDG4S0aR2j19IG+ludbpPcP95mYFVnGCb4rpj44iZoCifC8c9tVqC4L85hEGzik=
  matrix:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=dev
    - TRAVIS_CARGO_NIGHTLY_FEATURE=lint
