(function() {var implementors = {};
implementors['libc'] = [];implementors['capnp'] = ["impl&lt;S&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='capnp/message/struct.Reader.html' title='capnp::message::Reader'>Reader</a>&lt;S&gt; <span class='where'>where S: <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> + <a class='trait' href='capnp/message/trait.ReaderSegments.html' title='capnp::message::ReaderSegments'>ReaderSegments</a></span>","impl&lt;A&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='capnp/message/struct.Builder.html' title='capnp::message::Builder'>Builder</a>&lt;A&gt; <span class='where'>where A: <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> + <a class='trait' href='capnp/message/trait.Allocator.html' title='capnp::message::Allocator'>Allocator</a></span>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='capnp/private/arena/struct.SegmentBuilder.html' title='capnp::private::arena::SegmentBuilder'>SegmentBuilder</a>",];implementors['enum_primitive'] = [];implementors['leaf'] = ["impl&lt;B: <a class='trait' href='collenchyma/backend/trait.IBackend.html' title='collenchyma::backend::IBackend'>IBackend</a>&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Send.html' title='core::marker::Send'>Send</a> for <a class='struct' href='leaf/layer/struct.Layer.html' title='leaf::layer::Layer'>Layer</a>&lt;B&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
