(function() {var implementors = {};
implementors['libc'] = [];implementors['enum_primitive'] = [];implementors['rblas'] = ["impl&lt;'a, T&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='core::convert::Into'>Into</a>&lt;<a class='struct' href='https://doc.rust-lang.org/nightly/collections/vec/struct.Vec.html' title='collections::vec::Vec'>Vec</a>&lt;T&gt;&gt; for &amp;'a <a class='trait' href='rblas/vector/trait.Vector.html' title='rblas::vector::Vector'>Vector</a>&lt;T&gt; <span class='where'>where T: <a class='trait' href='rblas/vector/ops/trait.Copy.html' title='rblas::vector::ops::Copy'>Copy</a></span>",];implementors['leaf'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='core::convert::Into'>Into</a>&lt;<a class='enum' href='leaf/layer/enum.LayerType.html' title='leaf::layer::LayerType'>LayerType</a>&gt; for <a class='struct' href='leaf/layers/common/linear/struct.LinearConfig.html' title='leaf::layers::common::linear::LinearConfig'>LinearConfig</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='core::convert::Into'>Into</a>&lt;<a class='enum' href='leaf/layer/enum.LayerType.html' title='leaf::layer::LayerType'>LayerType</a>&gt; for <a class='struct' href='leaf/layers/loss/negative_log_likelihood/struct.NegativeLogLikelihoodConfig.html' title='leaf::layers::loss::negative_log_likelihood::NegativeLogLikelihoodConfig'>NegativeLogLikelihoodConfig</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='core::convert::Into'>Into</a>&lt;<a class='enum' href='leaf/layer/enum.LayerType.html' title='leaf::layer::LayerType'>LayerType</a>&gt; for <a class='struct' href='leaf/layers/utility/reshape/struct.ReshapeConfig.html' title='leaf::layers::utility::reshape::ReshapeConfig'>ReshapeConfig</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/convert/trait.Into.html' title='core::convert::Into'>Into</a>&lt;<a class='enum' href='leaf/layer/enum.LayerType.html' title='leaf::layer::LayerType'>LayerType</a>&gt; for <a class='struct' href='leaf/layers/container/sequential/struct.SequentialConfig.html' title='leaf::layers::container::sequential::SequentialConfig'>SequentialConfig</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
